import { adminNav, escapeHtml } from './admin-chrome';

export function renderLeadershipAdmin(email: string, env: Env, headers: Record<string, string>): Response {
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Pack 170 leadership editor</title><style>${css()}</style></head><body>
<a class="skip" href="#main">Skip to leadership editor</a><header><a class="brand" href="/"><span>170</span><div><b>Pack 170</b><small>Volunteer desk</small></div></a><nav>${adminNav('leadership')}</nav><div class="identity"><small>Signed in</small><strong>${escapeHtml(email)}</strong></div></header>
<main id="main"><section class="intro"><div><p class="tab">Pack leadership</p><h1>Leadership editor</h1><p>Change who holds each role. Saved names appear on the website immediately. Leave a name blank to show the role as open.</p></div><button class="primary" id="add-role">Add role</button></section>
<div id="status" class="status" role="status">Loading roster…</div><section class="roster-list" id="roster-list"></section></main><script>${script(env.ADMIN_ORIGIN)}</script></body></html>`;
  return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8', ...headers } });
}

function script(adminOrigin: string): string {
  return `const ORIGIN=${JSON.stringify(adminOrigin)},API='/api/admin/leadership';let roles=[];const list=document.querySelector('#roster-list'),status=document.querySelector('#status');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){status.textContent='Loading roster…';const r=await fetch(API);if(!r.ok){status.textContent='Unable to load the roster.';return;}roles=(await r.json()).roles;render();status.textContent=roles.length+(' role'+(roles.length===1?'':'s'));}
function render(){list.innerHTML=roles.map(role=>'<details class="role" data-id="'+esc(role.id)+'"><summary><b>'+esc(role.role)+'</b><span>'+(role.vacant?'Open':esc(role.name))+'</span></summary><div class="form-grid"><label class="wide">Role<input name="role" value="'+esc(role.role)+'" maxlength="120"></label><label class="wide">Name<input name="name" value="'+esc(role.name||'')+'" maxlength="120" placeholder="Leave blank if open"></label><label class="wide">Short bio<textarea name="bio" rows="3" maxlength="600">'+esc(role.bio||'')+'</textarea></label></div><div class="actions"><button type="button" class="secondary" data-remove>Remove role</button><button type="button" class="primary" data-save>Save</button></div></details>').join('');
list.querySelectorAll('[data-save]').forEach(b=>b.addEventListener('click',()=>save(b.closest('.role'))));
list.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>remove(b.closest('.role'))));}
function values(row){return{role:row.querySelector('[name=role]').value,name:row.querySelector('[name=name]').value,bio:row.querySelector('[name=bio]').value};}
async function save(row){status.textContent='Saving…';const r=await fetch(API+'/'+row.dataset.id,{method:'PUT',headers:{'content-type':'application/json','origin':ORIGIN},body:JSON.stringify(values(row))});const body=await r.json();status.textContent=r.ok?'Saved.':(body.error||'Unable to save.');if(r.ok)await load();}
async function remove(row){if(!confirm('Remove this role from the roster? This does not remove a person from the pack.'))return;const r=await fetch(API+'/'+row.dataset.id,{method:'DELETE',headers:{'origin':ORIGIN}});status.textContent=r.ok?'Role removed.':'Unable to remove that role.';if(r.ok)await load();}
document.querySelector('#add-role').addEventListener('click',async()=>{const role=prompt('What is the new role called?');if(!role)return;const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','origin':ORIGIN},body:JSON.stringify({role})});const body=await r.json();status.textContent=r.ok?'Role added.':(body.error||'Unable to add that role.');if(r.ok)await load();});
load();`;
}

// ponytail: leadership-admin gets its own local stylesheet rather than a shared adminCss()
// (human ruling, superseding the original plan) - copied from calendar-admin.ts's chrome
// rules since this is a brand-new page with no prior rendered output to preserve, plus the
// roster-specific rules the plan called out.
function css(): string {
  return `:root{--blue:#003f87;--deep:#002b5c;--gold:#fcd116;--paper:#f7f1e3;--page:#fffdf7;--ink:#272b2e;--muted:#59636b;--rule:#d7cdb8;--green:#28543f;--red:#a33c34}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.5 system-ui,sans-serif}button,input,select,textarea{font:inherit}:focus-visible{outline:4px solid var(--gold);outline-offset:3px}.skip{position:fixed;top:-5rem;left:1rem;background:var(--gold);color:var(--deep);padding:.75rem;z-index:10}.skip:focus{top:1rem}header{min-height:76px;padding:.75rem max(1rem,calc((100% - 1400px)/2));display:flex;align-items:center;gap:2rem;background:var(--deep);color:white;border-bottom:6px solid var(--gold)}.brand{display:flex;align-items:center;gap:.7rem;color:white;text-decoration:none}.brand>span{display:grid;place-items:center;width:44px;height:44px;border:3px solid var(--gold);border-radius:50%;color:var(--gold);font-weight:900}.brand b,.brand small,.identity b,.identity small{display:block}header nav{display:flex;align-self:stretch}header nav a{display:grid;place-items:center;padding:0 1rem;color:white;text-decoration:none;font-weight:700}header nav a[aria-current=page]{background:var(--gold);color:var(--deep)}.identity{margin-left:auto;text-align:right;min-width:0}.identity strong{overflow-wrap:anywhere}.identity small{color:#bed1e5}.tab{display:inline-block;margin:0 0 .4rem;padding:.3rem .65rem;border-radius:4px 10px 10px 4px;background:var(--gold);color:var(--deep);font-size:.74rem;font-weight:800;text-transform:uppercase}.primary,.secondary{min-height:46px;padding:.65rem 1rem;border:2px solid var(--deep);border-radius:8px 8px 3px;background:var(--blue);color:white;font-weight:800;cursor:pointer}.secondary{background:white;color:var(--deep)}main{width:min(1400px,calc(100% - 2rem));margin:2rem auto}.intro{display:flex;align-items:end;justify-content:space-between;gap:2rem}.intro h1{font-size:clamp(2.5rem,6vw,4.5rem);line-height:1;margin:0}.intro p:last-child{max-width:65ch}.status{min-height:1.5rem;margin:1.5rem 0 .7rem;color:var(--muted)}.form-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1rem}.form-grid label{display:grid;align-content:start;gap:.35rem;color:var(--deep);font-weight:800}.form-grid .wide{grid-column:1/-1}.form-grid input,.form-grid select,.form-grid textarea{width:100%;padding:.7rem;border:2px solid #8794a0;border-radius:7px 12px 6px;background:white;color:var(--ink);font-weight:400}@media(max-width:900px){header{flex-wrap:wrap}.identity{display:none}header nav{order:3;width:100%}.intro{align-items:start}.form-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){main{width:min(100% - 1rem,1400px)}.intro{display:grid}.form-grid{grid-template-columns:1fr}.form-grid .wide{grid-column:auto}}
.roster-list{display:grid;gap:.6rem}.role{background:var(--page);border:1px solid var(--rule);border-radius:8px}.role summary{display:flex;justify-content:space-between;gap:1rem;padding:1rem;cursor:pointer;font-weight:700}.role .form-grid{padding:0 1rem}.role .actions{display:flex;justify-content:flex-end;gap:.6rem;padding:1rem}`;
}
